### PR TITLE
Command rework

### PR DESCRIPTION
**Pull request by Moore2021**

### CODE REVIEW

**Comment by Moore2021** [comment]
This is still in progress I'll let you know when done @klerikdust

**Comment by klerikdust** [comment]
@Moore2021 are there any important version upgrades in one of the dependencies? Resolving the package-lock.json seems like a hassle lol. There are hundreds of lines to resolve.
If there aren't any important updates there, we'll be using the master's packages and discard this one.

**Comment by Moore2021** [comment]
@klerikdust is mostly versioning updates, The Plan is to update the node and npm versions, and then need to update the packages and rebuild the modules due to the new engine. If easier we can not include the package-lock in PR but after merge, this will more than likey happen again.

**Comment by klerikdust** [comment]
> @klerikdust is mostly versioning updates, The Plan is to update the node and npm versions, and then need to update the packages and rebuild the modules due to the new engine. If easier we can not include the package-lock in PR but after merge, this will more than likey happen again.

Oh if that's the case, i will just replace the master one with this then.

**Pull request merged**
