### PR TITLE
Quest change

### PR DESCRIPTION
**Pull request by Moore2021**
Support for multi-language during quests; will need help testing

### CODE REVIEW

**Review by klerikdust — CHANGES_REQUESTED** [review]
Wrap these quest-related functions into its own `Quest` class will be better in long run

**Comment by klerikdust** [comment]
```javascript
const session = new Quest(quest_id,)
//  Check if specified quest_id exists
if (!session.isValid) return
const isCorrectAnswer = session.answer(message.content)
if (!isCorrectAnswer) return
db.updateInventory({
  session.rewards.item_id,
  session.rewards.quantity,
  ...
})
```
Something similar to this. What do you think? @Moore2021

**Comment by Moore2021** [comment]
hmmm, possibly like so merge the one function i already did and turn it into a class and include the answering part as well?

**Pull request merged**
